### ISSUE TITLE
Compile error with Nim 2.0.4

### ISSUE THREAD

**Issue by panovr** [johnnovak/nim-raytracer#1]
Hi, when I tried to compile this program, there were some errors like:

`ui.nim(55, 30) Error: undeclared identifier: 'color'`

`ui.mim(75, 12) Error: undeclared identifier: 'mix'`

May you update the code to be compiled with Nim 2.0, thanks!

**Comment by johnnovak** [comment]
Thanks for your interest, but I'm not updating it as I've abandoned the project, technically.
